### ISSUE TITLE
Uploader Issue with Bootloader v2 

### ISSUE THREAD

**Issue by rblanchot** [PinguinoIDE/pinguino-ide#45]
I'm using a 18F4550, bootloader v2 with linux, something goes wrong when i upload code to board after compile with Pinguino 11-Beta3, x.4 and Beta 9-05 still work nice.
Code:
[DEBUG] Ending 'verify'
[DEBUG] Starting '__upload__' from 'qtgui.pinguino_api.pinguino_tools'
[DEBUG] Starting 'upload' from 'qtgui.pinguino_api.uploader.uploader'
[DEBUG] Looking for a Pinguino device ...
[DEBUG] Found device 0x04D8:0xFEAA
[DEBUG] Pinguino found
[DEBUG] OS is linux
[DEBUG] Configuration set
[DEBUG] Interface claimed
[DEBUG] Everything OK so far
[DEBUG] Traceback (most recent call last):
[DEBUG]   File '/usr/local/pinguino-11/qtgui/pinguino_api/tools.py', line 23, in inset
[DEBUG]     ret = f(*args, **kwaargs)
[DEBUG]   File '/usr/local/pinguino-11/qtgui/pinguino_api/uploader/uploader.py', line 173, in upload
[DEBUG]     self.uploader.uploadDevice(self.hexfile, self.board)
[DEBUG]   File '/usr/local/pinguino-11/qtgui/pinguino_api/uploader/uploaderVSC.py', line 287, in uploadDevice
[DEBUG]     status = self.writeHex(handle, filename, board)
[DEBUG]   File '/usr/local/pinguino-11/qtgui/pinguino_api/uploader/uploaderVSC.py', line 227, in writeHex
[DEBUG]     self.eraseBlock(handle, i)
[DEBUG] TypeError: eraseBlock() takes exactly 2 arguments (3 given)
[DEBUG]
[DEBUG] Traceback (most recent call last):
[DEBUG]   File '/usr/local/pinguino-11/qtgui/pinguino_api/tools.py', line 23, in inset
[DEBUG]     ret = f(*args, **kwaargs)
[DEBUG]   File '/usr/local/pinguino-11/qtgui/pinguino_api/pinguino_tools.py', line 228, in __upload__
[DEBUG]     result = filter(lambda line: not line.isspace(), result)
[DEBUG] TypeError: 'NoneType' object is not iterable
[DEBUG]

Definiton of eraseBlock in uploaderVSC.py:
   def eraseBlock(self, address):
        ...........
        self.writeFlash(handle, usbBuf)

Call from line 227:
self.eraseBlock(handle, i)

**Comment by CrusniK71** [comment]
Hi.

I'm using a Pinguino 18F2550 and Pinguino IDE 11-Beta3. I've tried both bootloader versions (1.x or 2.x and 4.x) with Windows 7 64 bit. I have successfully compiled an example blink.pde. But I can not upload it to the device. I get this messages instead. 

[OUT] Compiling: C:\pinguino-11\user\examples.Basics\Blink\Blink.pde
[OUT] Board: Pinguino 2550
[OUT] Proc: 18f2550
[OUT] Arch: 8
[OUT] Bootloader: v4
[DEBUG] Starting 'verify' from 'qtgui.pinguino_api.pinguino_tools'
[DEBUG] Starting 'preprocess' from 'qtgui.pinguino_api.pinguino_tools'
[DEBUG] Starting 'remove_comments' from 'qtgui.pinguino_api.pinguino_tools'
[DEBUG] Time spent for 'remove_comments': 0.00 s
[DEBUG] Ending 'remove_comments'
[DEBUG] Starting 'remove_comments' from 'qtgui.pinguino_api.pinguino_tools'
[DEBUG] Time spent for 'remove_comments': 0.00 s
[DEBUG] Ending 'remove_comments'
[DEBUG] Starting 'get_regobject_libinstructions' from 'qtgui.pinguino_api.pinguino_tools'
[DEBUG] Time spent for 'get_regobject_libinstructions': 0.00 s
[DEBUG] Ending 'get_regobject_libinstructions'
[DEBUG] Starting 'replace_word' from 'qtgui.pinguino_api.pinguino_tools'
[DEBUG] Time spent for 'replace_word': 0.01 s
[DEBUG] Ending 'replace_word'
[DEBUG] Time spent for 'preprocess': 0.06 s
[DEBUG] Ending 'preprocess'
[DEBUG] Starting 'compile' from 'qtgui.pinguino_api.pinguino_tools'
[DEBUG] Time spent for 'compile': 0.34 s
[DEBUG] Ending 'compile'
[DEBUG] Starting 'link' from 'qtgui.pinguino_api.pinguino_tools'
[DEBUG] Time spent for 'link': 0.16 s
[DEBUG] Ending 'link'
[DEBUG] Time spent for 'verify': 0.59 s
[DEBUG] Ending 'verify'
[OUT] compilation done
[OUT] Code size: 3448 / 29696 bytes (11% used)
[OUT] 0.593 seconds process time
[DEBUG] Starting '__upload__' from 'qtgui.pinguino_api.pinguino_tools'
[DEBUG] Starting 'upload' from 'qtgui.pinguino_api.uploader.uploader'
[DEBUG] Looking for a Pinguino device ...
[DEBUG] Found device 0x04D8:0xFEAA
[DEBUG] Pinguino found ...
[DEBUG] OS is windows
[DEBUG] Configuration set
[DEBUG] Interface claimed
[DEBUG] Everything OK so far
[DEBUG] Traceback (most recent call last):
[DEBUG]   File 'C:\pinguino-11\qtgui\pinguino_api	ools.py', line 23, in inset
[DEBUG]     ret = f(*args, **kwaargs)
[DEBUG]   File 'C:\pinguino-11\qtgui\pinguino_api\uploader\uploader.py', line 173, in upload
[DEBUG]     self.uploader.uploadDevice(self.hexfile, self.board)
[DEBUG]   File 'C:\pinguino-11\qtgui\pinguino_api\uploader\uploader8.py', line 487, in uploadDevice
[DEBUG]     device_id = self.getDeviceID(handle)
[DEBUG]   File 'C:\pinguino-11\qtgui\pinguino_api\uploader\uploader8.py', line 220, in getDeviceID
[DEBUG]     usbBuf = self.readFlash(handle, 0x3FFFFE, 2)
[DEBUG]   File 'C:\pinguino-11\qtgui\pinguino_api\uploader\uploader8.py', line 275, in readFlash
[DEBUG]     return self.sendCommand(handle, usbBuf)
[DEBUG]   File 'C:\pinguino-11\qtgui\pinguino_api\uploader\uploader8.py', line 171, in sendCommand
[DEBUG]     sent_bytes = handle.bulkWrite(self.OUT_EP, usbBuf, self.TIMEOUT)
[DEBUG]   File 'C:\Python27\lib\site-packages\usb\legacy.py', line 148, in bulkWrite
[DEBUG]     return self.dev.write(endpoint, buffer, self.__claimed_interface, timeout)
[DEBUG]   File 'C:\Python27\lib\site-packages\usb\core.py', line 625, in write
[DEBUG]     fn = fn_map[self._ctx.get_endpoint_type(self, endpoint, intf)]
[DEBUG]   File 'C:\Python27\lib\site-packages\usb\core.py', line 180, in get_endpoint_type
[DEBUG]     etype = util.endpoint_type(e.bmAttributes)
[DEBUG] AttributeError: 'NoneType' object has no attribute 'bmAttributes'
[DEBUG] 
[DEBUG] Traceback (most recent call last):
[DEBUG]   File 'C:\pinguino-11\qtgui\pinguino_api	ools.py', line 23, in inset
[DEBUG]     ret = f(*args, **kwaargs)
[DEBUG]   File 'C:\pinguino-11\qtgui\pinguino_api\pinguino_tools.py', line 228, in __upload__
[DEBUG]     result = filter(lambda line: not line.isspace(), result)
[DEBUG] TypeError: 'NoneType' object is not iterable
[DEBUG] 
>>> 

Please help.

**Comment by rblanchot** [comment]
Should be fixed in last version (18-05-2005).

**Comment by RenatoCorrea** [comment]
the problem still persists with me:

[OUT] compilation done
[OUT] Code size: 3448 / 29696 bytes (11% used)
[OUT] 0.670 seconds process time
[DEBUG] Starting '__upload__' from 'qtgui.pinguino_api.pinguino_tools'
[DEBUG] Starting 'upload' from 'qtgui.pinguino_api.uploader.uploader'
[DEBUG] Looking for a Pinguino device ...
[DEBUG] Traceback (most recent call last):
[DEBUG]   File 'C:\pinguino-11\qtgui\pinguino_api	ools.py', line 23, in inset
[DEBUG]     ret = f(*args, **kwaargs)
[DEBUG]   File 'C:\pinguino-11\qtgui\pinguino_api\uploader\uploader.py', line 177, in upload
[DEBUG]     self.uploader.uploadDevice(self.hexfile, self.board)
[DEBUG]   File 'C:\pinguino-11\qtgui\pinguino_api\uploader\uploader8.py', line 467, in uploadDevice
[DEBUG]     device = self.getDevice(board)
[DEBUG]   File 'C:\pinguino-11\qtgui\pinguino_api\uploader\uploader.py', line 76, in getDevice
[DEBUG]     busses = usb.busses()
[DEBUG]   File 'C:\Python27\lib\site-packages\usb\legacy.py', line 344, in busses
[DEBUG]     _interop._sorted(core.find(find_all=True), key=lambda d: d.bus),
[DEBUG]   File 'C:\Python27\lib\site-packages\usb\core.py', line 864, in find
[DEBUG]     raise ValueError('No backend available')
[DEBUG] ValueError: No backend available
[DEBUG] 
[DEBUG] Traceback (most recent call last):
[DEBUG]   File 'C:\pinguino-11\qtgui\pinguino_api	ools.py', line 23, in inset
[DEBUG]     ret = f(*args, **kwaargs)
[DEBUG]   File 'C:\pinguino-11\qtgui\pinguino_api\pinguino_tools.py', line 228, in __upload__
[DEBUG]     result = filter(lambda line: not line.isspace(), result)
[DEBUG] TypeError: 'NoneType' object is not iterable

Win7 64 using 18F2550 v2

Using pinguino-ide beta v11
tried downloading pinguino-ide repository from here(github) and replace files, but nothing changes
Am I losing something?

**Comment by CrusniK71** [comment]
Same here.

Win 7 64 bit using 18F2550 v2

Using pinguino-ide beta v11

The problem persists. Downloaded from the repository. Same error.

On Thu, Jun 4, 2015 at 10:38 AM, RenatoCorrea <notifications@github.com>
wrote:

> the problem still persists with me:
>
> [OUT] compilation done
> [OUT] Code size: 3448 / 29696 bytes (11% used)
> [OUT] 0.670 seconds process time
> [DEBUG] Starting '*upload*' from 'qtgui.pinguino_api.pinguino_tools'
> [DEBUG] Starting 'upload' from 'qtgui.pinguino_api.uploader.uploader'
> [DEBUG] Looking for a Pinguino device ...
> [DEBUG] Traceback (most recent call last):
> [DEBUG] File 'C:\pinguino-11\qtgui\pinguino_api ools.py', line 23, in inset
> [DEBUG] ret = f(*args, **kwaargs)
> [DEBUG] File 'C:\pinguino-11\qtgui\pinguino_api\uploader\uploader.py',
> line 177, in upload
> [DEBUG] self.uploader.uploadDevice(self.hexfile, self.board)
> [DEBUG] File 'C:\pinguino-11\qtgui\pinguino_api\uploader\uploader8.py',
> line 467, in uploadDevice
> [DEBUG] device = self.getDevice(board)
> [DEBUG] File 'C:\pinguino-11\qtgui\pinguino_api\uploader\uploader.py',
> line 76, in getDevice
> [DEBUG] busses = usb.busses()
> [DEBUG] File 'C:\Python27\lib\site-packages\usb\legacy.py', line 344, in
> busses
> [DEBUG]
>
>
>
>
>
>
>
> *interop.sorted(core.find(find_all=True), key=lambda d: d.bus), [DEBUG]
> File 'C:\Python27\lib\site-packages\usb\core.py', line 864, in find [DEBUG]
> raise ValueError('No backend available') [DEBUG] ValueError: No backend
> available [DEBUG] [DEBUG] Traceback (most recent call last): [DEBUG] File
> 'C:\pinguino-11\qtgui\pinguino_api ools.py', line 23, in inset [DEBUG] ret
> = f(args, *kwaargs) [DEBUG] File
> 'C:\pinguino-11\qtgui\pinguino_api\pinguino_tools.py', line 228, in
> __upload*
> [DEBUG] result = filter(lambda line: not line.isspace(), result)
> [DEBUG] TypeError: 'NoneType' object is not iterable
>
> Win7 64 using 18F2550 v2
>
> Using pinguino-ide beta v11
> tried downloading pinguino-ide repository from here(github) and replace
> files, but nothing changes
> Am I losing something?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PinguinoIDE/pinguino-ide/issues/45#issuecomment-108719061>
> .
>



-- 
Regards,

Mahmood Jasim
Lecturer
Department of Computer Science & Engineering
University of Dhaka

**Comment by YeisonEng** [comment]
Hi @RenatoCorrea @CrusniK71 
Right now I have not a Pinguino with v2 :/
Please, try with the last committed files and write the log generated.
https://github.com/PinguinoIDE/pinguino-ide/blob/master/qtgui/pinguino_api/pinguino_tools.py
https://github.com/PinguinoIDE/pinguino-ide/blob/master/qtgui/pinguino_api/uploader/uploader.py

**Comment by RenatoCorrea** [comment]
The log is the same, doesn't matter the pinguino is plugged or not. I can't test if the upload actually happened or not, unhappily. here is the log:

[OUT] compilation done
[OUT] Code size: 4098 / 24576 bytes (16% used)
[OUT] 0.689 seconds process time
[DEBUG] Starting '__upload__' from 'qtgui.pinguino_api.pinguino_tools'
[DEBUG] Starting 'upload' from 'qtgui.pinguino_api.uploader.uploader'
[DEBUG] Looking for a Pinguino device ...
[DEBUG] Traceback (most recent call last):
[DEBUG]   File 'C:\pinguino-11\qtgui\pinguino_api	ools.py', line 23, in inset
[DEBUG]     ret = f(*args, **kwaargs)
[DEBUG]   File 'C:\pinguino-11\qtgui\pinguino_api\uploader\uploader.py', line 177, in upload
[DEBUG]     self.uploader.uploadDevice(self.hexfile, self.board)
[DEBUG]   File 'C:\pinguino-11\qtgui\pinguino_api\uploader\uploaderVSC.py', line 256, in uploadDevice
[DEBUG]     device = self.getDevice(board)
[DEBUG]   File 'C:\pinguino-11\qtgui\pinguino_api\uploader\uploader.py', line 76, in getDevice
[DEBUG]     busses = usb.busses()
[DEBUG]   File 'C:\Python27\lib\site-packages\usb\legacy.py', line 344, in busses
[DEBUG]     _interop._sorted(core.find(find_all=True), key=lambda d: d.bus),
[DEBUG]   File 'C:\Python27\lib\site-packages\usb\core.py', line 864, in find
[DEBUG]     raise ValueError('No backend available')
[DEBUG] ValueError: No backend available
[DEBUG] 
[DEBUG] Time spent for '__upload__': 0.03 s
[DEBUG] Ending '__upload__'
[OUT]

**Comment by YeisonEng** [comment]
Hi @RenatoCorrea 
The log is different, this is a PyUSB bug.
Try reinstall PyUSB http://sourceforge.net/projects/pyusb/files/PyUSB%200.x/0.4.3/
and libusb http://www.libusb.org/

**Comment by RenatoCorrea** [comment]
Hi @YeisonEng 
thx for the help. reinstalling PyUSB solved the problem!
